import { Urbanist } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata = {
  title: "Estatein",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme='dark'> 
      <body className={`${urbanist.variable} ${urbanist.variable}`}>
        {children}
      </body>
    </html>
  );
}
